config/routes.rb
Rails.application.routes.draw do
  root 'visitors#index'
  get 'genre', to: 'visitors#genre', as: 'genre'
  get 'movie/:id', to: 'movies#show', as: 'movie'

  resources :reviews
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :rating, :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    @review = Review.new
    @movie = Tmdb::Movie.detail(params[:id])
    @movie_reviews = Review.where(movie: @movie.id).order('updated_at DESC')
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all.order('created_at DESC')
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.new(review_params)
    @review.save

    respond_to do |format|
      format.js
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update

  end

  def show

  end

  def delete

  end

  private
    def review_params
      params.require(:review).permit(:user, :rating, :comment, :movie)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController


  def index

    @sort_by = params["sort_by"]
    @upcoming = Tmdb::Movie.now_playing(region: 'US')['results'][0..5]
    @reviews = @upcoming.map{|movie| Tmdb::Movie.reviews(movie["id"]).results.first }

    @page = params[:page].nil? ? 1 : params[:page]

    if @sort_by.nil?
      @sort_by = "popular"
      @data = Tmdb::Movie.popular(page: @page, region: 'US')
    elsif @sort_by == "top_rated"
      @data = Tmdb::Movie.top_rated(page: @page, region: 'US')
    elsif @sort_by == "now_playing"
      @data = Tmdb::Movie.now_playing(page: @page, region: 'US')
    elsif @sort_by == "upcoming"
      @data = Tmdb::Movie.upcoming(page: @page, region: 'US')
    elsif @sort_by == "genre"
      @data = Tmdb::Genre.movies(params[:genre].to_i)
    else
      @sort_by = "popular"
      @data = Tmdb::Movie.popular(page: @page, region: 'US')
    end


    @movies = @data['results']
    @total_pages = @data['total_pages']
    @total_results = @data['total_results']

    respond_to do |format|
      format.html
      format.js
    end
  end

  def genre


    respond_to do |format|
      format.html { render 'visitors/index' }
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def get_genre(id)
    # TODO: sort the data manually and use binary search to find id
    data = '{"genres":[{"id":28,"name":"Action"}, {"id":12,"name":"Adventure"},{"id":16,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"},{"id":99,"name":"Documentary"},{"id":18,"name":"Drama"},{"id":10751,"name":"Family"},{"id":14,"name":"Fantasy"},{"id":36,"name":"History"},{"id":27,"name":"Horror"},{"id":10402,"name":"Music"},{"id":9648,"name":"Mystery"},{"id":10749,"name":"Romance"},{"id":878,"name":"Science Fiction"},{"id":10770,"name":"TV Movie"},{"id":53,"name":"Thriller"},{"id":10752,"name":"War"},{"id":37,"name":"Western"}]}'
    genres = JSON.parse(data)["genres"]
    for genre in genres
      if genre["id"] == id
        return genre["name"]
      end
    end
    "Other"
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <div class="inlineBlock link"><%= link_to 'Edit account', edit_user_registration_path %></div>
  <div class="inlineBlock link"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></div>
<% else %>
  <div class="inlineBlock link"><%= link_to 'Sign in', new_user_session_path %></div>
  <div class="inlineBlock link"><%= link_to 'Sign up', new_user_registration_path %></div>
<% end %>

<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <div class="inlineBlock link"><%= link_to 'Users', users_path %></div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div id="top" style="height:165px; border-bottom: 1px solid lightgrey;">
  <div id="header" class="vertCenterRight">
    <%= link_to root_path do %>
        <div id="logo" class="posAbs lato vertCenterLeft">
          <%= image_tag 'icon.png', height: '50px', width: '50px', class: 'inlineBlock vertAlignTop', style: 'margin-right:20px;margin-left:0;' %>RipeTomatoes
        </div>
    <% end %>
    <div class="inlineBlock link"><%= link_to 'Movies', root_path %></div>
    <div class="inlineBlock link"><%= link_to 'Reviews', reviews_path %></div>
    <div class="inlineBlock link"><%= link_to 'About', page_path('about') %></div>
    <%= render 'layouts/nav_links_for_auth' %>
  </div>
  <div id="sorting">
    <div class="inlineBlock posRel" style="font-weight:700;font-family: 'Open Sans', sans-serif;
        font-size: 1.2em;
        padding: 0 15px;">Sort By</div>
    <div id="popular" class="inlineBlock sortingLink posRel"><%= link_to 'Popular', root_path %></div>
    <div id="top_rated" class="inlineBlock sortingLink posRel"><%= link_to 'Top Rated', root_path(sort_by: "top_rated") %></div>
    <div id="now_playing" class="inlineBlock sortingLink posRel"><%= link_to 'Now Playing', root_path(sort_by: "now_playing") %></div>
    <div id="upcoming" class="inlineBlock sortingLink posRel"><%= link_to 'Release Date', root_path(sort_by: "upcoming") %></div>
    <div class="inlineBlock sortingLink posRel"><%= link_to 'Title', root_path %></div>
    <div id="genre" class="inlineBlock sortingLink posRel"><a data-toggle="popover" title="Pick a Genre" data-content='
    <a href="<%=root_path(sort_by:"genre", genre: 28)%>"><button type="button" class="btn btn-primary">Action</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 12)%>"><button type="button" class="btn btn-primary">Adventure</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 16)%>"><button type="button" class="btn btn-primary">Animation</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 35)%>"><button type="button" class="btn btn-primary">Comedy</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 80)%>"><button type="button" class="btn btn-primary">Crime</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 99)%>"><button type="button" class="btn btn-primary">Documentary</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 18)%>"><button type="button" class="btn btn-primary">Drama</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 10751)%>"><button type="button" class="btn btn-primary">Family</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 14)%>"><button type="button" class="btn btn-primary">Fantasy</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 36)%>"><button type="button" class="btn btn-primary">History</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 27)%>"><button type="button" class="btn btn-primary">Horror</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 10402)%>"><button type="button" class="btn btn-primary">Music</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 9648)%>"><button type="button" class="btn btn-primary">Mystery</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 10749)%>"><button type="button" class="btn btn-primary">Romance</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 878)%>"><button type="button" class="btn btn-primary">Science Fiction</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 10770)%>"><button type="button" class="btn btn-primary">TV Movie</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 53)%>"><button type="button" class="btn btn-primary">Thriller</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 10752)%>"><button type="button" class="btn btn-primary">War</button></a>
    <a href="<%=root_path(sort_by:"genre", genre: 37)%>"><button type="button" class="btn btn-primary">Western</button></a>
    ' data-placement="bottom" class="pointer">Genre</a></div>
  </div>
</div>

<script>
  var sorting_link = $(".sortingLink");
  var red_line = '<div class="posAbs sortingLine" style="bottom:-20px;left:0;right:0;height:6px;background-color:#E85256;border-top-left-radius:8px;border-top-right-radius:8px;"></div>';

  sorting_link.mouseenter(function(){
    $(this).append(red_line)
  });
  sorting_link.mouseleave(function(){
    if ($(this).attr('id') != '<%=@sort_by%>'){
      $(this).find('.sortingLine').remove();
    }
  });
  $("#<%=@sort_by%>").append(red_line);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=0.75">
    <title><%= content_for?(:title) ? yield(:title) : "RipeTomatoes" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>

    <!-- JQuery -->
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900|Lora:400,700|Merriweather:300i,400i|Open+Sans:300,400,600" rel="stylesheet">

    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>
  <body class="posRel">
    <%= image_tag 'pattern.png', class: "posAbs", style: "top:0;height:100%;z-index:0;opacity:0.9;" %>
    <div id="main_content">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>

      <div class="posRel" style="overflow-y:scroll;height:100%;width:100%;">
        <%= yield %>
      </div>
    </div>
  </body>

</html>

app/views/movies/_movie.html.erb
<div class="movie vertCenterLeft overflowHidden" style="height:300px;margin-bottom:30px;background-color:white;
    border:1px solid lightgrey; border-radius:3px;
    -webkit-box-shadow: 0px 5px 10px 0px #ddd;
    -moz-box-shadow: 0px 5px 10px 0px #ddd;
    box-shadow: 0px 5px 10px 0px #ddd;">
  <!-- Image -->
  <% if movie["poster_path"].nil? %>
      <img src="http://www.valmorgan.com.au/wp-content/uploads/2016/06/default-movie-1-3.jpg" height="300px" width="200px" /><!-- create link to image -->
  <% else %>
      <img src="<%="https://image.tmdb.org/t/p/original/"+movie["poster_path"]%>" height="300px" width="200px" /><!-- create link to image -->
  <% end %>

  <!-- Information -->
  <div class="information posRel" style="width:720px;height:300px;padding-left:25px;padding-top:15px;padding-right:25px;">
    <% unless movie["title"].nil? %>
        <%= link_to movie_path(id: movie["id"]) do %>
            <div class="title lora" style="font-size:2.1em;font-weight:700;margin-bottom:10px;">
              <%= (movie["title"].length > 22) ? movie["title"][0, 22]+"..." : movie["title"] %>
            </div>
        <% end %>
    <% end %>

    <% unless movie["release_date"].nil? or movie["release_date"].empty? %>
        <div class="release" style="font-size:1.3em;margin-bottom:20px;color: #4BC5FF;">Released on <%= DateTime.strptime(movie["release_date"], '%Y-%m-%d').strftime('%b %d, %Y') %></div>
    <% end %>

    <% unless movie["overview"].nil? %>
        <div class="overview opens" style="font-size:1.25em;font-weight:400;margin-bottom:20px;line-height:1.3em;color:grey;">
          <%= (movie["overview"].length > 200) ? movie["overview"][0, 200]+"...": movie["overview"] %>
        </div>
    <% end %>

    <% unless movie["genre_ids"].nil? %>
        <div class="genres posAbs" style="margin-bottom:15px;left:25px;right:25px;bottom:0;">
          <% movie["genre_ids"].each do |genre_id| %>
              <div class="inlineBlock opens" style="margin-bottom:5px;font-weight:700;background-color:#E85256;border-radius:15px;height:27px;font-size:1.1em;color:white;margin-right:10px;padding:3px 12px 2px 12px;"><%= get_genre(genre_id) %></div>
          <% end %>
        </div>
    <% end %>

    <div class="posAbs" style="right:12px;top:12px;height:65px;">
      <% if not movie["vote_average"].nil? and not (movie["vote_average"]/2).round == 0 %>
          <div class="vertCenterRight" style="border:1px solid grey;border-radius:5px;">
            <% (movie["vote_average"]/2).round.times do %>
                <%= image_tag 'star.png', height: '25px', width: '25px', style: 'margin-left:15px;' %>
            <% end %>
            <div class="opens vertCenterMiddle opens" style="color:white;font-weight:700;font-size:1.7em;background-color:grey;padding:0 10px 0 12px;margin-left:15px;height:40px;"><%= (movie["vote_average"]/2) %></div>
          </div>
      <% else %>
          <div class="opens vertCenterMiddle opens" style="color:white;font-weight:700;font-size:1.7em;background-color:grey;padding:0 10px 0 12px;margin-left:15px;height:40px;border-radius:5px;">Not Rated</div>
      <% end %>
      <div class="rightText" style="margin-top:12px;color:gray;font-size:1.1em;">
        <%= link_to 'See Reviews (' + Review.where(movie: movie["id"]).count.to_s + ')', movie_path(id: movie["id"]), class: 'inlineBlock vertAlignTop' %>
      </div>
    </div>


  </div>
</div>

app/views/movies/show.html.erb
<div class="leftText" style="background-color: #f4f4f4;padding:40px;">

  <div class="" style="width:100%;">
    <div class="inlineBlock vertAlignTop" style="width:350px;margin:0 20px;">
      <% if @movie["poster_path"].nil? %>
          <img src="http://www.valmorgan.com.au/wp-content/uploads/2016/06/default-movie-1-3.jpg" width="350px" /><!-- create link to image -->
      <% else %>
          <img src="<%="https://image.tmdb.org/t/p/original"+@movie["poster_path"]%>" width="350px" style="-webkit-box-shadow: 0px 5px 10px 0px #666;
              -moz-box-shadow: 0px 5px 10px 0px #666;
              box-shadow: 0px 5px 10px 0px #666;" /><!-- create link to image -->
      <% end %>

      <% if not @movie["vote_average"].nil? and not (@movie["vote_average"]/2).round == 0 %>
          <div class="vertCenterMiddle" style="border:1px solid grey;border-radius:5px;margin-top:15px;padding-left:10px;">
            <% (@movie["vote_average"]/2).round.times do %>
                <%= image_tag 'star.png', height: '35px', width: '35px', style: '' %>
            <% end %>
            <div class="opens vertCenterMiddle opens" style="color:white;font-weight:700;font-size:1.7em;background-color:grey;padding:0 10px 0 12px;margin-left:15px;height:56px;"><%= (@movie["vote_average"]/2) %></div>
          </div>
      <% else %>
          <div class="opens vertCenterMiddle opens" style="color:white;font-weight:700;font-size:1.7em;background-color:grey;padding:0 10px 0 12px;margin-left:15px;height:56px;border-radius:5px;">Not Rated</div>
      <% end %>

      <% unless @movie["release_date"].nil? or @movie["release_date"].empty? %>
          <div class="centerText" style="font-size:1.4em;margin-top:30px;color: #4BC5FF;">Released on <%= DateTime.strptime(@movie["release_date"], '%Y-%m-%d').strftime('%b %d, %Y') %></div>
      <% end %>
    </div>

    <div class="inlineBlock vertAlignTop" style="width:800px;padding-left:20px;">
      <% unless @movie["title"].nil? %>
          <div class="title lora" style="font-size:3em;font-weight:700;margin-bottom:5px;">
            <%= @movie["title"] %>
          </div>
      <% end %>

      <% unless @movie["tagline"].nil? or @movie["tagline"].empty? %>
          <div class="merri" style="font-size:1.4em;margin-top:20px;margin-bottom:30px;"><%= @movie["tagline"] %></div>
      <% end %>

      <% unless @movie["overview"].nil? %>
          <div class="overview opens" style="font-size:1.4em;font-weight:400;margin-bottom:35px;line-height:1.3em;color:grey;">
            <%= @movie["overview"] %>
          </div>
      <% end %>

      <% unless @movie["genres"].nil? %>
          <div class="genres" style="margin-bottom:15px;">
            <% @movie["genres"].each do |genre| %>
                <div class="inlineBlock opens" style="margin-bottom:5px;font-weight:700;background-color:#E85256;border-radius:15px;height:27px;font-size:1.1em;color:white;margin-right:10px;padding:3px 12px 4px 12px;"><%= genre["name"] %></div>
            <% end %>
          </div>
      <% end %>

      <!-- Create a review for this menu -->
      <% if current_user %>
          <div style="border-top:1px solid lightgrey;border-bottom:1px solid lightgrey;padding: 20px 0;margin: 25px 0;">
            <%= form_for(@review, remote: true) do |f| %>
                <%= f.hidden_field :movie, value: @movie.id %>

                <%= f.label :rating %><br>
                <div class="rating vertCenterLeft">
                  <%= f.radio_button :rating, 5, :id => 'star5' %><label for="star5"></label>
                  <%= f.radio_button :rating, 4, :id => 'star4'  %><label for="star4"></label>
                  <%= f.radio_button :rating, 3, :id => 'star3'  %><label for="star3"></label>
                  <%= f.radio_button :rating, 2, :id => 'star2'  %><label for="star2"></label>
                  <%= f.radio_button :rating, 1, :id => 'star1'  %><label for="star1"></label>
                </div>

                <%= f.label :comment %><br>
                <%= f.text_area :comment, placeholder: 'Write your review here!', style: 'height:150px;width:700px;font-size:1.5em;padding:10px;' %>

                <div><%= f.submit 'Submit', style:'border:none;background-color:#E85256;border-radius:5px;color:white;font-weight:400;padding:10px 25px;font-size:1.5em;margin-top:15px;' %></div>
            <% end %>
          </div>
      <% else %>
          <div style="border-top:1px solid lightgrey;border-bottom:1px solid lightgrey;padding: 20px 0;margin: 25px 0;font-size:2em;">
            You must be logged in to write a review
          </div>
      <% end %>

      <!-- All reviews for this menu -->
      <div id="review_list">
        <% @movie_reviews.each do |review| %>
          <%= render 'reviews/movie_review', review: review %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<div style="padding:30px 55px;font-size:1.5em;height:calc(105vh);background-color:white;">
  <h3>Website created by Varun Shivakumar</h3>
  <p>
    Linkedin: <a href="https://www.linkedin.com/in/varunshivakumar">https://www.linkedin.com/in/varunshivakumar</a>
  </p>
  <p>
    <b>Styling</b><br/> Completely custom with hints of boostrap.
    TODO: refractor inline css into scss
  </p>
  <p>
    <b>Page Layout</b><br/>
    Home page: Click on home -> see all movies and sort by popularity or genre<br/>
    Movie page: Click on movie title -> see movie specific information as well as that movies reviews<br/>
    Review page: Click on Reviews in header -> see all reviews created in this database<br/>
  </p>
  <p>
    <b>Models</b><br/> Only Review and User. I excluded the Movie model because all the information is stored in "The Movie Database API".
    We could use the seed file to query for every movie and store the details in our own database.
  </p>
  <p>
    <b>Gems</b><br/>
    Tmdb (for movie details)<br/>
    Devise (for secure user login/signup)<br/>
    Rspec (for testing) <br/>
  </p>
  <p>
    <b>Testing (Rspec)</b><br/>
    $ spec/models/review_spec.rb
  </p>
  <p>
    <b>Github</b><br/>
    https://github.com/varunshivakumar/ripetomatoes
  </p>
  <p>
    <b>Database and Hosting</b><br/>
    Database: Postgresql<br/>
    Heroku: https://limitless-dawn-75562.herokuapp.com/
  </p>
  <br/>
  <!--
  <p>
    What does sort by title mean? Alphabetically?<br/>
    Should I load reviews from Tmdb or are they all custom?<br/>
    Do you have to be logged in to rate a movie? Otherwise how would you get their email?
    Wouldn't it make more sense for the review to list their username and not email?
  </p>
  -->
</div>

app/views/reviews/_movie_review.html.erb
<div class="posRel" style="margin-bottom:35px;">

  <div class="opens" style="font-size:1.8em;margin-bottom:15px;font-weight:400;"><%= review.comment %></div>
  <div class="merri" style="font-size:1.4em;margin-bottom:15px;color:gray;">
    <% review.rating.times do %>
        <%= image_tag 'star.png', height: '20px', width: '20px', class: 'inlineBlock vertAlignTop', style: 'margin-right:10px;margin-top:2px;' %>
    <% end %>
    <div class="inlineBlock vertAlignTop"><%= review.user.email %> <span style="margin: 0 5px">on</span> <%= review.created_at.strftime('%b %d, %Y') %></div>
  </div>
</div>

app/views/reviews/_side_review.html.erb
<div class="posRel" style="margin-bottom:35px;">
  <div class="lora" style="font-size:1.5em;margin-bottom:10px;font-weight:700;"><%= link_to movie["original_title"], movie_path(id: movie["id"])%></div>
  <% if false %>
      <div style="font-size:1.3em;margin-bottom:15px;color: #4BC5FF;">Released on</div>
  <% end %>
  <div class="opens" style="font-size:1.2em;margin-bottom:15px;font-weight:400;color:gray;"><%= review["content"].length > 300 ? review["content"][0..300]+"..." : review["content"] %></div>
  <div class="merri centerText" style="font-size:1.5em;margin-bottom:15px;"><%= review["author"] %></div>
  <div class="lato posAbs" style="top:-1px;right:2px;font-size:1.5em;margin-bottom:15px;font-weight:700;"><%= (movie["vote_average"]/2).round %> / 5</div>
</div>

app/views/reviews/create.js.erb
$("#review_list").prepend("<%= j render 'reviews/movie_review', review: @review %>");

$("#new_review")[0].reset();

app/views/reviews/index.html.erb
<div style="background-color: #f4f4f4;padding:40px;">
  <%= render @reviews %>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div style="background-color: #f4f4f4;padding-top:30px;">
  <div id="movie_list" class="textContent inlineBlock vertAlignTop" style="padding-left:25px;padding-right:20px;width:67%">
    <% if not @movies.nil? and @movies.any? %>
        <% @movies.each do |movie| %>
            <%= render 'movies/movie', movie: movie %>
        <% end %>
    <% end %>

    <div id="load_more_container">
      <%= link_to root_path(page: @page+1), remote: true do %>
          <div id="load_more" class="opens vertCenterMiddle" style="color:white;background-color:#E85256;border-radius:5px;font-size:2em;width:200px;height:50px;margin: 30px auto;font-weight:700;">Load More</div>
      <% end %>
    </div>
  </div>
  <div class="inlineBlock vertAlignTop" style="width:31%">
    <div class="textContent" style="background-color:white;-webkit-box-shadow: 0px 5px 10px 0px #ddd;
        -moz-box-shadow: 0px 5px 10px 0px #ddd;
        box-shadow: 0px 5px 10px 0px #ddd;
        border:1px solid lightgrey;padding:30px;padding-bottom:0;">
      <div class="lora" style="font-size:1.7em;border-bottom: 1px solid lightgrey;padding-bottom:20px;margin-bottom:20px;font-weight:700;">
        Recent Reviews
        <div class="inlineBlock rightText" style="font-size:0.9em;margin-left:100px;"><%= link_to 'See All', reviews_path %></div>
      </div>
      <% (0..5).each do |i| %>
          <% if (not @upcoming[i].nil?) and (not @reviews[i].nil?) %>
              <%= render 'reviews/side_review', movie: @upcoming[i], review: @reviews[i] %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>